#! /bin/sh

HOSTIP=$(hostname -I | cut -d " " -f1)
docker run \
	--name alexa \
	--mount type=bind,source=$PWD/run/database,target=/alexa/database \
	--mount type=bind,source=$PWD/run/config,target=/alexa/config \
	--mount type=bind,source=$PWD/run/GUI,target=/alexa/GUI \
	--mount type=bind,source=/dev/snd,target=/dev/snd \
	--network host \
	--env HOSTIP="${HOSTIP}" \
	--rm \
	--privileged \
	-it \
	alexa
